version: '3.8'
services:
  image-handler-ms:
    image: "ghcr.io/kexogg/hackathon-rzhd-2024-backend:backend"
    env_file:
      - ../.env
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"